language: node_js
node_js:
  - '11.6.0'


branches:
  only:
    - master
env:
  global:
    - REMOTEAPPDIR=/var/www/light-it-08.tk/
    - REMOTEUSER=usr01
    - REMOTEHOST=188.166.54.169 # your droplet IP goes here
    - PORT=54231

cache:
  directories:
    - ./node_modules

install:
  - npm install --only=dev

script:
  - chmod 600 deploy && mv deploy ~/.ssh/idrsa
  - echo "hello world $REMOTEAPPDIR $REMOTEUSER $REMOTEHOST $PORT"
  - ssh -p$PORT $REMOTEUSER@$REMOTEHOST "ls -la /"

