before_install:
- openssl aes-256-cbc -K $encrypted_81a46f29ae8f_key -iv $encrypted_81a46f29ae8f_iv
  -in travis.enc -out travis -d
- echo "ls travis -ls"
- chmod 600 travis
- echo "ls travis -ls"
- mv travis ~/.ssh/id_rsa

language: node_js
node_js:
- 11.6.0

branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/light-it-08.tk/
  - REMOTEUSER=usr01
  - REMOTEHOST=188.166.54.169
  - PORT=54231

script:
  - npm install
  - npm run build --prod
  - ssh -o "StrictHostKeyChecking=no" -p$PORT $REMOTEUSER@$REMOTEHOST "ls -la"
  - tar -czf package.tgz ./dist/travis
  - ssh -o "StrictHostKeyChecking=no" -p$PORT $REMOTEUSER@$REMOTEHOST "rm -rf /var/www/light-it-08.tk/*"
  - scp -P$PORT package.tgz $REMOTEUSER@$REMOTEHOST:/var/www/light-it-08.tk/
  - ssh -p$PORT $REMOTEUSER@$REMOTEHOST "cd /var/www/light-it-08.tk/ && tar -xvf /var/www/light-it-08.tk/package.tgz"
  - ssh -o "StrictHostKeyChecking=no" -p$PORT $REMOTEUSER@$REMOTEHOST "ls -la /var/www/light-it-08.tk/"
#  - bash ./scripts/deploy.sh
