language: node_js
node_js:
- 11.6.0
addons:
  ssh_known_hosts: 188.166.54.169:54231

before_install:
    - openssl aes-256-cbc -K $encrypted_81a46f29ae8f_key -iv $encrypted_81a46f29ae8f_iv
      -in travis.enc -out travis -d
      - chmod 600 travis
      - mv travis ~/.ssh/id_rsa
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/light-it-08.tk/
  - REMOTEUSER=usr01
  - REMOTEHOST=188.166.54.169
  - PORT=54231

script:
- bash ./scripts/deploy.sh
