before_install:
- openssl aes-256-cbc -K $encrypted_81a46f29ae8f_key -iv $encrypted_81a46f29ae8f_iv
  -in travis.enc -out travis -d
language: node_js
node_js:
- 11.6.0

branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/light-it-08.tk/
  - REMOTEUSER=usr01
  - REMOTEHOST=188.166.54.169
  - PORT=54231
beforescript:
- chmod 600 deploy && mv deploy ~/.ssh/idrsa
script:
- bash ./scripts/deploy.sh
